### PR TITLE
Fix issues

### PR DESCRIPTION
**Pull request by iTofu**
[#1](https://github.com/PrPrLive/TKSubmitTransitionSwift3/issues/1): Conflict between `@IBInspectable` and `CGFloat`
[#2](https://github.com/PrPrLive/TKSubmitTransitionSwift3/issues/2): `cornerRadius` should be reset when animation be finished

### CODE REVIEW

**Comment by iTofu** [comment]
@TareqElMasri 
Hi guy, take a look :)

**Comment by TareqElMasriDev** [comment]
@iTofu I'm sorry I didn't notice your comment, I will like into it and I will run my test and merge it

**Comment by iTofu** [comment]
That's fine, you could review the commits before [4980340](https://github.com/TareqElMasri/TKSubmitTransitionSwift3/pull/1/commits/498034078f045263986e12483a4822a203e0df1e), after this commit it's my company's demand and I'm so sorry I forget create a branch...

**Comment by iTofu** [comment]
Closed because content changed incorrectly.

**Pull request closed without merging**
